### ISSUE TITLE
Support for multiple streams at a time

### ISSUE THREAD

**Issue by ChirappaVishnupriya** [akhil-rana/virtual-bg#7]
ERROR Error: Uncaught (in promise): **RuntimeError: abort(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)**) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:69361)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:69537)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:43094)
    at Object.get (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:24082)
    at https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:23905
    at qa.h (http://localhost:4200/vendor.js:29137:414)
    at ta (http://localhost:4200/vendor.js:29101:299)
    at ua.next (http://localhost:4200/vendor.js:29102:91)
    at http://localhost:4200/vendor.js:29127:619
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:4544:29)
RuntimeError: abort(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:69361)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:69537)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:43094)
    at Object.get (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:24082)
    at https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:23905
    at qa.h (http://localhost:4200/vendor.js:29137:414)
    at ta (http://localhost:4200/vendor.js:29101:299)
    at ua.next (http://localhost:4200/vendor.js:29102:91)
    at http://localhost:4200/vendor.js:29127:619
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:4544:29)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:43125)
    at Object.get (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:24082)
    at https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation_solution_simd_wasm_bin.js:9:23905
    at qa.h (http://localhost:4200/vendor.js:29137:414)
    at ta (http://localhost:4200/vendor.js:29101:299)
    at ua.next (http://localhost:4200/vendor.js:29102:91)
    at http://localhost:4200/vendor.js:29127:619
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:4544:29)
    at Y (http://localhost:4200/vendor.js:29127:389)
    at http://localhost:4200/vendor.js:29137:254
    at resolvePromise (http://localhost:4200/polyfills.js:4328:31)
    at http://localhost:4200/polyfills.js:4235:17
    at rejected (http://localhost:4200/vendor.js:378694:89)
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:3489:26)
    at Object.onInvoke (http://localhost:4200/vendor.js:440180:33)
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:3488:52)
    at Zone.run (http://localhost:4200/polyfills.js:3251:43)
    at http://localhost:4200/polyfills.js:4392:36
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3523:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:440167:33)

**Comment by akhil-rana** [comment]
Working with multiple streams at the same time is not supported officially right now.

But there's a workaround suggested by someone else (another user) so I cannot guarantee this..

`I have found a work around. I clone the virtual-bg.js to a new file. And in that file, I need to import mediapipe library separately. So I call the clone functions of the new file, and it works well`

Also please note that if you are able to do it by this method, it can be very very resource heavy depending on the user's system configuration.

**Comment by ChirappaVishnupriya** [comment]
ok ,cloning file and work around is for multiple streams?

**Comment by akhil-rana** [comment]
> ok ,cloning file and work around is for multiple streams?

Yeah, it basically makes two clones of the library and you can call the seprate clones from separate streams.

Please let me know if it works for you.

**Comment by ChirappaVishnupriya** [comment]
ok sure

**Comment by ChirappaVishnupriya** [comment]
**I have tried by cloning below files and still i am facing same issue**
       

>  selfie_segmentation_landscape.tflite
>         selfie_segmentation_solution_simd_wasm_bin.data
>         selfie_segmentation_solution_simd_wasm_bin.js
>         selfie_segmentation_solution_simd_wasm_bin.wasm
>         selfie_segmentation_solution_wasm_bin.js
>         selfie_segmentation_solution_wasm_bin.wasm
>         selfie_segmentation.binarypb
>         selfie_segmentation.js
>         selfie_segmentation.tflite

Please let me know anyother i have to clone.
Thanks.
